"""add embedded_at to companies

Revision ID: 0b38224aad6e
Revises: 8ba0f1056a9e
Create Date: 2026-03-23 18:02:12.578455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b38224aad6e'
down_revision: Union[str, Sequence[str], None] = '8ba0f1056a9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('embedded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'embedded_at')
    # ### end Alembic commands ###
