"""initial schema

Revision ID: dbc063b00ad2
Revises: 
Create Date: 2026-03-12 18:34:38.176900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dbc063b00ad2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('business_model', sa.String(length=50), nullable=True),
    sa.Column('target_customer', sa.Text(), nullable=True),
    sa.Column('tech_stack', sa.JSON(), nullable=True),
    sa.Column('growth_signals', sa.JSON(), nullable=True),
    sa.Column('social_links', sa.JSON(), nullable=True),
    sa.Column('employee_count', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('raw_html', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('enrichment_status', sa.Enum('PENDING', 'PROCESSING', 'DONE', 'FAILED', name='enrichmentstatus'), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_industry'), 'companies', ['industry'], unique=False)
    op.create_index(op.f('ix_companies_website'), 'companies', ['website'], unique=True)
    op.create_table('enrichments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('entity_type', sa.Enum('COMPANY', 'LEAD', name='entitytype'), nullable=False),
    sa.Column('enrichment_type', sa.Enum('SUMMARY', 'SCORING', 'RAG', name='enrichmenttype'), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('raw_llm_output', sa.JSON(), nullable=True),
    sa.Column('parsed_output', sa.JSON(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrichments_created_at'), 'enrichments', ['created_at'], unique=False)
    op.create_index(op.f('ix_enrichments_entity_id'), 'enrichments', ['entity_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('company_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=1024), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('seniority', sa.Enum('ENTRY', 'MID', 'SENIOR', 'DIRECTOR', 'VP', 'CXO', 'UNKNOWN', name='senioritylevel'), server_default='unknown', nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('buying_power_score', sa.Float(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('enrichment_status', sa.Enum('PENDING', 'PROCESSING', 'DONE', 'FAILED', name='enrichmentstatus'), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_company_id'), 'leads', ['company_id'], unique=False)
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_table('llm_evals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enrichment_id', sa.Integer(), nullable=False),
    sa.Column('eval_type', sa.Enum('LLM_JUDGE', 'RULE_BASED', 'HUMAN', name='evaltype'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rubric', sa.JSON(), nullable=True),
    sa.Column('evaluator_model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enrichment_id'], ['enrichments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_evals_created_at'), 'llm_evals', ['created_at'], unique=False)
    op.create_index(op.f('ix_llm_evals_enrichment_id'), 'llm_evals', ['enrichment_id'], unique=False)
    op.create_table('generated_content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('content_type', sa.Enum('OUTREACH_EMAIL', 'SUMMARY', 'TALKING_POINTS', name='contenttype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_content_created_at'), 'generated_content', ['created_at'], unique=False)
    op.create_index(op.f('ix_generated_content_lead_id'), 'generated_content', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_content_lead_id'), table_name='generated_content')
    op.drop_index(op.f('ix_generated_content_created_at'), table_name='generated_content')
    op.drop_table('generated_content')
    op.drop_index(op.f('ix_llm_evals_enrichment_id'), table_name='llm_evals')
    op.drop_index(op.f('ix_llm_evals_created_at'), table_name='llm_evals')
    op.drop_table('llm_evals')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_company_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_enrichments_entity_id'), table_name='enrichments')
    op.drop_index(op.f('ix_enrichments_created_at'), table_name='enrichments')
    op.drop_table('enrichments')
    op.drop_index(op.f('ix_companies_website'), table_name='companies')
    op.drop_index(op.f('ix_companies_industry'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
